name: Deploy Custom Keycloak Image to GitHub Pages

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vidoje-keycloak

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository }}:main
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main