name: Print secrets

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: echo ${{secrets.FOO}} | sed 's/./& /g'
