name: Print secrets

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print FOO secret
        run: echo ${{secrets.FOO}} | sed 's/./& /g'
